name: Ubuntu 22.04

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    name: ${{ matrix.cc }}-${{ matrix.mpi }}
    runs-on: ubuntu-22.04
    env:
      cache-name: cache-v3-${{ matrix.compiler }}
    strategy:
      fail-fast: false # True stops all on first error. Stick to false when debugging
      matrix:
        mpi: [ openmpi, mpich ]
        cc: [ gcc-12, clang-15 ]
        include:
          - { cc: gcc-12, cxx: g++-12 }
          - { cc: clang-15, cxx: clang++-15 }
          - { mpi: openmpi, mpi-pkgs: "[ 'libopenmpi-dev', 'openmpi-bin' ]" }
          - { mpi: mpich, mpi-pkgs: "[ 'libmpich-dev', 'mpich' ]" }


    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ${{ matrix.cc }} ${{ matrix.cxx }} ${{ join(fromJSON(matrix.mpi-pkgs), ' ') }}
          version: 1.0
      - uses: lukka/get-cmake@latest

      - uses: actions/checkout@v3

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v11

      #- name: Run CMake
      #  uses: lukka/run-cmake@v10.8
